### ISSUE TITLE
Problem with sort_vertices

### ISSUE THREAD

**Issue by LucBourrat1** [Visual-Behavior/aloception#112]
Error when training a model with DETR:

/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/tgey/.local/lib/python3.8/site-packages/sort_vertices-0.0.0-py3.8-linux-x86_64.egg/sort_vertices.cpython-38-x86_64-linux-gnu.so)

**Comment by thibo73800** [comment]
https://github.com/Visual-Behavior/aloception/pull/114
