### ISSUE TITLE
print(onnx_export_log) is " "

### ISSUE THREAD

**Issue by wm901115nwpu** [Visual-Behavior/aloception#198]
with ExitStack() as stack:
    # context managers necessary to redirect stdout and modify export trace to print scope
    buffer = stack.enter_context(io.StringIO())
    stack.enter_context(redirect_stdout(buffer))
    stack.enter_context(scope_name_workaround())
    torch.onnx.export(
                net,  # model being run
                dummy_input,  # model input (or a tuple for multiple inputs)
                'resnet18.onnx',  # where to save the model
                export_params=True,  # store the trained parameter weights inside the model file
                opset_version=13,  # the ONNX version to export the model to
                do_constant_folding=True,  # whether to execute constant folding for optimization
                verbose=False,  # verbose mandatory in scope names procedure
            )
    onnx_export_log = buffer.getvalue()
print(onnx_export_log) is " "

**Comment by thibo73800** [comment]
Hi @wm901115nwpu  can you give more details about your issue and the way to reproduce ?
