### ISSUE TITLE
Sintel : saved samples

### ISSUE THREAD

**Issue by thibo73800** [Visual-Behavior/aloception#27]
`SintelDataset` has been splitted into `SintelFlowDataset` and `SintelDisparityDataset`. We also added `SintelMultiDataset`.

The dataset samples should be updated accordingly.
------

Actually, the saved samples should be generated again for all dataset containing flow or disparity:

- [x] FlyingChairs2Dataset
- [x] ChairsSDHomDataset
- [x] SintelFlowDataset
- [x] SintelDisparityDataset
- [x] SintelMultiDataset
- [x] FlyingThings3DSubsetDataset (replace FlyingThingsDataset ; not merged in main yet)

This is due to a modification to `aloscene.io.mask.load_mask`. This modifications ensures that Mask data is between 0 and 1. Therefore, the previously saved samples don't have correct values for Mask objects.

**Comment by Johansmm** [comment]
This is a feature will implement in #1

**Comment by thibo73800** [comment]
@Johansmm could be close this one then ?
