### ISSUE TITLE
Exported sample get exported randomly. Therefore, sequence is not preserved when using `strem_loader()`

### ISSUE THREAD

**Issue by thibo73800** [Visual-Behavior/aloception#51]
The exported sample. (For instance the sample of MOT17) get exported randomly. Therefore using `stream_loader` we get a random sequence of frame instead of frames from the same sequence.

To reproduce: 

```python
import alodataset

mot_dataset = alodataset.Mot17(sample=True, validation_sequences=["MOT17-05"])

for frames in mot_dataset.stream_loader():
    frames.names
    frames.get_view( ).render()
```

In the following I would expect `stream_loader` to go through all the samples, while each sequence belongs to the same sequence.  Also I think its ok if each sample return by stream_loader get a dimension T=2. By doing so the sample can be logical both using the train_loader and the strem_loader.

For other non-sequential dataset, its fine to have stream_loader returning random sample since there is no sequence.

**Comment by Johansmm** [comment]
Done. We need update the samples in google cloud.
