### ISSUE TITLE
when viewing a training progress with tensorboard, the nb of epochs seems to be multiplied by 2, is it ok?

### ISSUE THREAD

**Issue by LucBourrat1** [Visual-Behavior/aloception#54]

**Comment by thibo73800** [comment]
@ragier  any ideas ?

**Comment by ragier** [comment]
what's your batch_size and your accumulate_grad_batches ?

**Comment by LucBourrat1** [comment]
batch_size = 1 and accumulate_grad_batches not precised, so the one by default I guess

**Comment by thibo73800** [comment]
@ragier @LucBourrat1  should we close this issue ?
