### ISSUE TITLE
Update COCO dataset and COCODetection to detr with  SplitMix class

### ISSUE THREAD

**Issue by Johansmm** [Visual-Behavior/aloception#79]
Update COCO detection with SplitMix class.

**Comment by thibo73800** [comment]
I'm not sure it is possible right now since splitMix is used for datasets with a `Split` while Coco dataset is file based (ann, img_folder)

**Comment by Johansmm** [comment]
I will work in a proposition and will make a pull request with the considerations. We could discuss then.
